### ISSUE TITLE
should docs/crow be docs/modular/crow?

### ISSUE THREAD

**Issue by csboling** [monome/docs#126]
Perhaps an unimportant detail but surprised me for a moment when I tried to change a URL bar from the Ansible docs to the Crow docs. I realize this would probably break some URLs elsewhere, maybe /docs/crow could redirect to /docs/modular/crow or vice versa. Seems nice for consistency, especially if there were a desire to have a /docs/modular page giving a high level overview of all the modular stuff.

**Comment by tehn** [comment]
i'm looking to migrate all of the module docs to a shorter url, ie monome/docs/teletype

i'll work on some redirects, and i apologize for the inconsistency--- indeed it's frustrating for the moment
