### ISSUE TITLE
Teletype Studies 5

### ISSUE THREAD

**Issue by unity2k** [monome/docs#14]
Please change the reference from ~ to Tab and NumLock to get to the Tracker

**Comment by nightmorph** [comment]
i made a pull request that fixes this bug with this commit:

https://github.com/monome/docs/commit/52ff40432bdad4676f9527a9e438f42f8045fda5

...which updates all references to tilde and the tracker throughout the docs. not just the studies, but also their linked example scenes.

(not sure why this pullreq got added into my earlier pullreq that was on the ansible docs; github shouldn't have lumped them together like that!)

**Comment by nightmorph** [comment]
fixed!
