### ISSUE TITLE
Saving TT files

### ISSUE THREAD

**Issue by unity2k** [monome/docs#16]
The following information is missing from the user manual:

Scenes that are saved from the TT will be stored as

tt00s.txt
on your flash drive. The numbers will be the scene number and note the “s”.
To load something from the flash drive you just need to rename the file, and leave off the “s”.

To load the mlr.txt file to scene number 10 you rename the file to

tt10.txt
and place it on your flash drive.

**Comment by nightmorph** [comment]
This info was put in the Teletype manual awhile back; see this section:

https://monome.org/docs/modular/teletype/manual/#usb-backup
