### ISSUE TITLE
make Vimeo embeds responsive

### ISSUE THREAD

**Issue by jlmitch5** [monome/docs#187]
Currently for product pages, the Vimeo embed at the top is not responsive, so things horizontally scroll on mobile.  See the root teletype doc page for example.

**Comment by tehn** [comment]
thanks for spotting this. any ideas for a fix?

**Comment by nattog** [comment]
My Ruby installs are a mess so haven't been able to test locally but try selecting responsive sizing when generating the Vimeo embed code:

![Screenshot 2019-11-09 at 10 05 04](https://user-images.githubusercontent.com/38443772/68526882-8a9da480-02d8-11ea-8021-46924ebf7f33.png)

**Comment by tehn** [comment]
fixed 7d534c6..33681d0
