### ISSUE TITLE
Advanced.md doc

### ISSUE THREAD

**Issue by unity2k** [monome/docs#19]
The "advanced.md" in the Teletype/docs directory has a drawing explaining the PRE / POST terminology that is not currently in the user manual. I find this helpful and think others would too.

**Comment by samdoshi** [comment]
Looks like it is to me: https://monome.org/docs/modular/teletype/manual/#advanced

**Comment by unity2k** [comment]
Sure enough. It's even in the PDF which I missed as with 154 results searching for "pre" I hadn't considered it might be below the operators for the various other modules and I had "assumed" I'd find it in the main Teletype help section. My bad.
