### ISSUE TITLE
tt usb disk txt needs to get in the manual

### ISSUE THREAD

**Issue by tehn** [monome/docs#20]
https://github.com/monome/docs/blob/a00b371c45c7f3edf7826a006e5efae4cb8d8a47/docs/modular/teletype/index.md#usb-flash-drive-scene-readwrite

**Comment by nightmorph** [comment]
This info was put in the Teletype manual awhile back; see this section:

https://monome.org/docs/modular/teletype/manual/#usb-backup

Not sure when it was added; but that was what was fixes the request in the duplicate bug #16 .
