### ISSUE TITLE
proposal of installing all-contributors bot

### ISSUE THREAD

**Issue by montoyamoraga** [monome/docs#215]
i propose installing the all-contributors bot
https://allcontributors.org/
i really like what we have done at the p5.js repo
https://github.com/processing/p5.js
where we celebrate all contributions,
i think it makes everyone in the community happier
:)

**Comment by tehn** [comment]
i appreciate the sentiment, but i believe the "contributors" tab is adequate and visually much more appealing: https://github.com/monome/docs/graphs/contributors
