### ISSUE TITLE
Small typo in Arc documentation

### ISSUE THREAD

**Issue by mwilliams** [monome/docs#323]
Would have opened a PR with the fix myself, but I couldn't seem to find the source material that these pages are building from  as I see the docs are automatically built using LDoc

But for the `Arc:segment (ring, from, to, level)` description, the word `specific` is spelled incorrectly: `on a sepcific LED ring.`

The typo exists in the following lines as seen rendered out here https://monome.org/docs/norns/api/modules/arc.html#Arc:segment:
- https://github.com/monome/docs/blob/gh-pages/norns/api/classes/arc.html#L331
- https://github.com/monome/docs/blob/gh-pages/norns/api/modules/arc.html#L129

**Comment by tehn** [comment]
this api doc is auto-generated from the lua code.


fixed by https://github.com/monome/norns/pull/1458


copied to docs and published
